# Generated by Django 4.2.6 on 2023-10-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projectaccount", "0010_subject_role"),
        ("store", "0002_student_semester"),
    ]

    operations = [
        migrations.CreateModel(
            name="TheoryInternalMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("se1", models.IntegerField(blank=True, null=True)),
                ("se2", models.IntegerField(blank=True, null=True)),
                ("se3", models.IntegerField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_name",
                        to="store.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Theory_subject",
                        to="projectaccount.subject",
                    ),
                ),
            ],
        ),
    ]
