# Generated by Django 4.2.6 on 2023-10-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_theoryinternalmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="theoryinternalmark",
            name="assignment1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="theoryinternalmark",
            name="assignment2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="theoryinternalmark",
            name="assignment3",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
