# Generated by Django 4.2.6 on 2023-10-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_theoryinternalmark_assignment1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theoryinternalmark",
            name="attendance_percentage",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
