# Generated by Django 4.2.6 on 2023-10-25 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projectaccount", "0010_subject_role"),
        ("store", "0006_theoryinternalmark_semester"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabInternalMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test1", models.IntegerField(blank=True, null=True)),
                ("test2", models.IntegerField(blank=True, null=True)),
                ("rough_record_mark", models.IntegerField(blank=True, null=True)),
                ("fair_record_mark", models.IntegerField(blank=True, null=True)),
                ("lab_work_mark", models.IntegerField(blank=True, null=True)),
                ("open_ended_mark", models.IntegerField(blank=True, null=True)),
                ("attendance_mark", models.IntegerField(blank=True, null=True)),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_Lab_mark",
                        to="projectaccount.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Lab_student_name",
                        to="store.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Lab_subject",
                        to="projectaccount.subject",
                    ),
                ),
            ],
        ),
    ]
