# Generated by Django 4.2.6 on 2023-10-12 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projectaccount", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="email",
            field=models.EmailField(
                blank=True, max_length=60, null=True, unique=True, verbose_name="email"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="roll_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_name",
                to="projectaccount.subject",
            ),
        ),
    ]
