# Generated by Django 4.2.6 on 2023-10-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectaccount", "0002_subject_account_email_account_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="password",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
