# Generated by Django 4.2.6 on 2023-10-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectaccount", "0003_alter_account_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="passwords",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="password",
            field=models.CharField(default=1, max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
    ]
