# Generated by Django 4.2.6 on 2023-10-12 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectaccount", "0004_account_passwords_alter_account_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="passwords",
            new_name="copy_pass",
        ),
    ]
