# Generated by Django 4.2.6 on 2023-10-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectaccount", "0006_semester_account_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="semester",
        ),
        migrations.AddField(
            model_name="account",
            name="semester",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="semester_name",
                to="projectaccount.semester",
            ),
        ),
    ]
