# Generated by Django 4.2.6 on 2023-10-23 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projectaccount", "0007_remove_account_semester_account_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semester_subject",
                to="projectaccount.semester",
            ),
        ),
    ]
