# Generated by Django 4.2.6 on 2023-10-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectaccount", "0008_subject_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="semester",
            field=models.ManyToManyField(
                related_name="semester_name", to="projectaccount.semester"
            ),
        ),
        migrations.RemoveField(
            model_name="account",
            name="subject",
        ),
        migrations.AddField(
            model_name="account",
            name="subject",
            field=models.ManyToManyField(
                related_name="subject_name", to="projectaccount.subject"
            ),
        ),
    ]
