# Generated by Django 4.2.6 on 2023-10-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projectaccount",
            "0009_alter_account_semester_remove_account_subject_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
